/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GameFactory {
  export type GameConfigStruct = {
    toolName: string;
    toolSymbol: string;
    resourceName: string;
    resourceSymbol: string;
    toolDuration: BigNumberish;
    activateOnMint: boolean;
    expiredTransferable: boolean;
    initialRewards: BigNumberish;
    dailyEmissionCap: BigNumberish;
    seasonEmissionCap: BigNumberish;
    emissionStart: BigNumberish;
    emissionEnd: BigNumberish;
    baseReward: BigNumberish;
    cooldown: BigNumberish;
    durabilityCost: BigNumberish;
    levelMultiplierBps: BigNumberish;
    powerMultiplierBps: BigNumberish;
    upgradeCost: BigNumberish;
    upgradePowerIncrease: BigNumberish;
    upgradeDurabilityIncrease: BigNumberish;
  };

  export type GameConfigStructOutput = [
    toolName: string,
    toolSymbol: string,
    resourceName: string,
    resourceSymbol: string,
    toolDuration: bigint,
    activateOnMint: boolean,
    expiredTransferable: boolean,
    initialRewards: bigint,
    dailyEmissionCap: bigint,
    seasonEmissionCap: bigint,
    emissionStart: bigint,
    emissionEnd: bigint,
    baseReward: bigint,
    cooldown: bigint,
    durabilityCost: bigint,
    levelMultiplierBps: bigint,
    powerMultiplierBps: bigint,
    upgradeCost: bigint,
    upgradePowerIncrease: bigint,
    upgradeDurabilityIncrease: bigint
  ] & {
    toolName: string;
    toolSymbol: string;
    resourceName: string;
    resourceSymbol: string;
    toolDuration: bigint;
    activateOnMint: boolean;
    expiredTransferable: boolean;
    initialRewards: bigint;
    dailyEmissionCap: bigint;
    seasonEmissionCap: bigint;
    emissionStart: bigint;
    emissionEnd: bigint;
    baseReward: bigint;
    cooldown: bigint;
    durabilityCost: bigint;
    levelMultiplierBps: bigint;
    powerMultiplierBps: bigint;
    upgradeCost: bigint;
    upgradePowerIncrease: bigint;
    upgradeDurabilityIncrease: bigint;
  };

  export type ToolTypeConfigStruct = {
    toolType: BigNumberish;
    price: BigNumberish;
    maxSupply: BigNumberish;
    power: BigNumberish;
    durability: BigNumberish;
    metadataURI: string;
  };

  export type ToolTypeConfigStructOutput = [
    toolType: bigint,
    price: bigint,
    maxSupply: bigint,
    power: bigint,
    durability: bigint,
    metadataURI: string
  ] & {
    toolType: bigint;
    price: bigint;
    maxSupply: bigint;
    power: bigint;
    durability: bigint;
    metadataURI: string;
  };
}

export interface GameFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "VERSION"
      | "createGame"
      | "registry"
      | "registryAdmin"
      | "setGameStatus"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GameCreated"): EventFragment;

  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [GameFactory.GameConfigStruct, GameFactory.ToolTypeConfigStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registryAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGameStatus",
    values: [BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registryAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameStatus",
    data: BytesLike
  ): Result;
}

export namespace GameCreatedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    operator: AddressLike,
    toolNFT: AddressLike,
    miningCore: AddressLike,
    resourceToken: AddressLike,
    rewardVault: AddressLike,
    version: string
  ];
  export type OutputTuple = [
    gameId: bigint,
    operator: string,
    toolNFT: string,
    miningCore: string,
    resourceToken: string,
    rewardVault: string,
    version: string
  ];
  export interface OutputObject {
    gameId: bigint;
    operator: string;
    toolNFT: string;
    miningCore: string;
    resourceToken: string;
    rewardVault: string;
    version: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameFactory extends BaseContract {
  connect(runner?: ContractRunner | null): GameFactory;
  waitForDeployment(): Promise<this>;

  interface: GameFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  VERSION: TypedContractMethod<[], [string], "view">;

  createGame: TypedContractMethod<
    [
      config: GameFactory.GameConfigStruct,
      toolTypes: GameFactory.ToolTypeConfigStruct[]
    ],
    [
      [bigint, string, string, string, string, string] & {
        gameId: bigint;
        toolNFT: string;
        miningCore: string;
        resourceToken: string;
        rewardVault: string;
        ruleModule: string;
      }
    ],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  registryAdmin: TypedContractMethod<[], [string], "view">;

  setGameStatus: TypedContractMethod<
    [gameId: BigNumberish, status: BigNumberish, riskTag: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [
      config: GameFactory.GameConfigStruct,
      toolTypes: GameFactory.ToolTypeConfigStruct[]
    ],
    [
      [bigint, string, string, string, string, string] & {
        gameId: bigint;
        toolNFT: string;
        miningCore: string;
        resourceToken: string;
        rewardVault: string;
        ruleModule: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registryAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGameStatus"
  ): TypedContractMethod<
    [gameId: BigNumberish, status: BigNumberish, riskTag: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;

  filters: {
    "GameCreated(uint256,address,address,address,address,address,string)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
  };
}
