/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GameRegistry {
  export type GameRecordStruct = {
    gameId: BigNumberish;
    operator: AddressLike;
    factory: AddressLike;
    toolNFT: AddressLike;
    miningCore: AddressLike;
    resourceToken: AddressLike;
    rewardVault: AddressLike;
    version: string;
    status: BigNumberish;
    riskTag: string;
    exists: boolean;
  };

  export type GameRecordStructOutput = [
    gameId: bigint,
    operator: string,
    factory: string,
    toolNFT: string,
    miningCore: string,
    resourceToken: string,
    rewardVault: string,
    version: string,
    status: bigint,
    riskTag: string,
    exists: boolean
  ] & {
    gameId: bigint;
    operator: string;
    factory: string;
    toolNFT: string;
    miningCore: string;
    resourceToken: string;
    rewardVault: string;
    version: string;
    status: bigint;
    riskTag: string;
    exists: boolean;
  };

  export type ProtocolReleaseStruct = {
    version: string;
    factory: AddressLike;
    metadataURI: string;
    active: boolean;
    exists: boolean;
  };

  export type ProtocolReleaseStructOutput = [
    version: string,
    factory: string,
    metadataURI: string,
    active: boolean,
    exists: boolean
  ] & {
    version: string;
    factory: string;
    metadataURI: string;
    active: boolean;
    exists: boolean;
  };
}

export interface GameRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedRegistrars"
      | "getGame"
      | "getProtocolRelease"
      | "getRecommendedUpgrade"
      | "migrationURIOf"
      | "nextGameId"
      | "owner"
      | "previousGameOf"
      | "recommendGameUpgrade"
      | "recommendedUpgradeOf"
      | "registerGame"
      | "setGameStatus"
      | "setProtocolRelease"
      | "setRegistrar"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameRegistered"
      | "GameStatusUpdated"
      | "GameUpgradeRecommended"
      | "OwnershipTransferred"
      | "ProtocolReleaseUpdated"
      | "RegistrarUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedRegistrars",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolRelease",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecommendedUpgrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "migrationURIOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextGameId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previousGameOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recommendGameUpgrade",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recommendedUpgradeOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerGame",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameStatus",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolRelease",
    values: [string, AddressLike, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrar",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedRegistrars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecommendedUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrationURIOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextGameId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previousGameOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recommendGameUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recommendedUpgradeOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace GameRegisteredEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    operator: AddressLike,
    factory: AddressLike,
    toolNFT: AddressLike,
    miningCore: AddressLike,
    resourceToken: AddressLike,
    rewardVault: AddressLike,
    version: string
  ];
  export type OutputTuple = [
    gameId: bigint,
    operator: string,
    factory: string,
    toolNFT: string,
    miningCore: string,
    resourceToken: string,
    rewardVault: string,
    version: string
  ];
  export interface OutputObject {
    gameId: bigint;
    operator: string;
    factory: string;
    toolNFT: string;
    miningCore: string;
    resourceToken: string;
    rewardVault: string;
    version: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStatusUpdatedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    status: BigNumberish,
    riskTag: string
  ];
  export type OutputTuple = [gameId: bigint, status: bigint, riskTag: string];
  export interface OutputObject {
    gameId: bigint;
    status: bigint;
    riskTag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameUpgradeRecommendedEvent {
  export type InputTuple = [
    fromGameId: BigNumberish,
    toGameId: BigNumberish,
    operator: AddressLike,
    migrationURI: string
  ];
  export type OutputTuple = [
    fromGameId: bigint,
    toGameId: bigint,
    operator: string,
    migrationURI: string
  ];
  export interface OutputObject {
    fromGameId: bigint;
    toGameId: bigint;
    operator: string;
    migrationURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolReleaseUpdatedEvent {
  export type InputTuple = [
    version: string,
    factory: AddressLike,
    metadataURI: string,
    active: boolean
  ];
  export type OutputTuple = [
    version: string,
    factory: string,
    metadataURI: string,
    active: boolean
  ];
  export interface OutputObject {
    version: string;
    factory: string;
    metadataURI: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrarUpdatedEvent {
  export type InputTuple = [registrar: AddressLike, authorized: boolean];
  export type OutputTuple = [registrar: string, authorized: boolean];
  export interface OutputObject {
    registrar: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GameRegistry;
  waitForDeployment(): Promise<this>;

  interface: GameRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedRegistrars: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: BigNumberish],
    [GameRegistry.GameRecordStructOutput],
    "view"
  >;

  getProtocolRelease: TypedContractMethod<
    [version: string],
    [GameRegistry.ProtocolReleaseStructOutput],
    "view"
  >;

  getRecommendedUpgrade: TypedContractMethod<
    [gameId: BigNumberish],
    [[bigint, string] & { toGameId: bigint; migrationURI: string }],
    "view"
  >;

  migrationURIOf: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  nextGameId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  previousGameOf: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  recommendGameUpgrade: TypedContractMethod<
    [fromGameId: BigNumberish, toGameId: BigNumberish, migrationURI: string],
    [void],
    "nonpayable"
  >;

  recommendedUpgradeOf: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  registerGame: TypedContractMethod<
    [
      operator: AddressLike,
      toolNFT: AddressLike,
      miningCore: AddressLike,
      resourceToken: AddressLike,
      rewardVault: AddressLike,
      version: string
    ],
    [bigint],
    "nonpayable"
  >;

  setGameStatus: TypedContractMethod<
    [gameId: BigNumberish, status: BigNumberish, riskTag: string],
    [void],
    "nonpayable"
  >;

  setProtocolRelease: TypedContractMethod<
    [
      version: string,
      factory: AddressLike,
      metadataURI: string,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  setRegistrar: TypedContractMethod<
    [registrar: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedRegistrars"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [GameRegistry.GameRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocolRelease"
  ): TypedContractMethod<
    [version: string],
    [GameRegistry.ProtocolReleaseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecommendedUpgrade"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [[bigint, string] & { toGameId: bigint; migrationURI: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "migrationURIOf"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "nextGameId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previousGameOf"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "recommendGameUpgrade"
  ): TypedContractMethod<
    [fromGameId: BigNumberish, toGameId: BigNumberish, migrationURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recommendedUpgradeOf"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerGame"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      toolNFT: AddressLike,
      miningCore: AddressLike,
      resourceToken: AddressLike,
      rewardVault: AddressLike,
      version: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGameStatus"
  ): TypedContractMethod<
    [gameId: BigNumberish, status: BigNumberish, riskTag: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProtocolRelease"
  ): TypedContractMethod<
    [
      version: string,
      factory: AddressLike,
      metadataURI: string,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRegistrar"
  ): TypedContractMethod<
    [registrar: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "GameRegistered"
  ): TypedContractEvent<
    GameRegisteredEvent.InputTuple,
    GameRegisteredEvent.OutputTuple,
    GameRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "GameStatusUpdated"
  ): TypedContractEvent<
    GameStatusUpdatedEvent.InputTuple,
    GameStatusUpdatedEvent.OutputTuple,
    GameStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GameUpgradeRecommended"
  ): TypedContractEvent<
    GameUpgradeRecommendedEvent.InputTuple,
    GameUpgradeRecommendedEvent.OutputTuple,
    GameUpgradeRecommendedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolReleaseUpdated"
  ): TypedContractEvent<
    ProtocolReleaseUpdatedEvent.InputTuple,
    ProtocolReleaseUpdatedEvent.OutputTuple,
    ProtocolReleaseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RegistrarUpdated"
  ): TypedContractEvent<
    RegistrarUpdatedEvent.InputTuple,
    RegistrarUpdatedEvent.OutputTuple,
    RegistrarUpdatedEvent.OutputObject
  >;

  filters: {
    "GameRegistered(uint256,address,address,address,address,address,address,string)": TypedContractEvent<
      GameRegisteredEvent.InputTuple,
      GameRegisteredEvent.OutputTuple,
      GameRegisteredEvent.OutputObject
    >;
    GameRegistered: TypedContractEvent<
      GameRegisteredEvent.InputTuple,
      GameRegisteredEvent.OutputTuple,
      GameRegisteredEvent.OutputObject
    >;

    "GameStatusUpdated(uint256,uint8,string)": TypedContractEvent<
      GameStatusUpdatedEvent.InputTuple,
      GameStatusUpdatedEvent.OutputTuple,
      GameStatusUpdatedEvent.OutputObject
    >;
    GameStatusUpdated: TypedContractEvent<
      GameStatusUpdatedEvent.InputTuple,
      GameStatusUpdatedEvent.OutputTuple,
      GameStatusUpdatedEvent.OutputObject
    >;

    "GameUpgradeRecommended(uint256,uint256,address,string)": TypedContractEvent<
      GameUpgradeRecommendedEvent.InputTuple,
      GameUpgradeRecommendedEvent.OutputTuple,
      GameUpgradeRecommendedEvent.OutputObject
    >;
    GameUpgradeRecommended: TypedContractEvent<
      GameUpgradeRecommendedEvent.InputTuple,
      GameUpgradeRecommendedEvent.OutputTuple,
      GameUpgradeRecommendedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProtocolReleaseUpdated(string,address,string,bool)": TypedContractEvent<
      ProtocolReleaseUpdatedEvent.InputTuple,
      ProtocolReleaseUpdatedEvent.OutputTuple,
      ProtocolReleaseUpdatedEvent.OutputObject
    >;
    ProtocolReleaseUpdated: TypedContractEvent<
      ProtocolReleaseUpdatedEvent.InputTuple,
      ProtocolReleaseUpdatedEvent.OutputTuple,
      ProtocolReleaseUpdatedEvent.OutputObject
    >;

    "RegistrarUpdated(address,bool)": TypedContractEvent<
      RegistrarUpdatedEvent.InputTuple,
      RegistrarUpdatedEvent.OutputTuple,
      RegistrarUpdatedEvent.OutputObject
    >;
    RegistrarUpdated: TypedContractEvent<
      RegistrarUpdatedEvent.InputTuple,
      RegistrarUpdatedEvent.OutputTuple,
      RegistrarUpdatedEvent.OutputObject
    >;
  };
}
