/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "GameFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GameFactory__factory>;
    getContractFactory(
      name: "GameRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GameRegistry__factory>;
    getContractFactory(
      name: "MiningCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiningCore__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ResourceToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ResourceToken__factory>;
    getContractFactory(
      name: "RewardVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardVault__factory>;
    getContractFactory(
      name: "RuleModuleV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RuleModuleV1__factory>;
    getContractFactory(
      name: "ToolNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ToolNFT__factory>;

    getContractAt(
      name: "GameFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GameFactory>;
    getContractAt(
      name: "GameRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GameRegistry>;
    getContractAt(
      name: "MiningCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MiningCore>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ResourceToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ResourceToken>;
    getContractAt(
      name: "RewardVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardVault>;
    getContractAt(
      name: "RuleModuleV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RuleModuleV1>;
    getContractAt(
      name: "ToolNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ToolNFT>;

    deployContract(
      name: "GameFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GameFactory>;
    deployContract(
      name: "GameRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GameRegistry>;
    deployContract(
      name: "MiningCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MiningCore>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ResourceToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ResourceToken>;
    deployContract(
      name: "RewardVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardVault>;
    deployContract(
      name: "RuleModuleV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RuleModuleV1>;
    deployContract(
      name: "ToolNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ToolNFT>;

    deployContract(
      name: "GameFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GameFactory>;
    deployContract(
      name: "GameRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GameRegistry>;
    deployContract(
      name: "MiningCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MiningCore>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ResourceToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ResourceToken>;
    deployContract(
      name: "RewardVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardVault>;
    deployContract(
      name: "RuleModuleV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RuleModuleV1>;
    deployContract(
      name: "ToolNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ToolNFT>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
