/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MiningCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canMine"
      | "mine"
      | "mineBatch"
      | "owner"
      | "paused"
      | "pendingReward"
      | "resourceToken"
      | "rewardVault"
      | "ruleModule"
      | "setPaused"
      | "setRuleModule"
      | "setUpgradeConfig"
      | "toolNFT"
      | "transferOwnership"
      | "upgradeCost"
      | "upgradeDurabilityIncrease"
      | "upgradePowerIncrease"
      | "upgradeTool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Mined"
      | "OwnershipTransferred"
      | "ParameterChanged"
      | "Paused"
      | "RuleModuleUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canMine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mine", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "mineBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resourceToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ruleModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setRuleModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUpgradeConfig",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "toolNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeDurabilityIncrease",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradePowerIncrease",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTool",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "canMine", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mine", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mineBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resourceToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ruleModule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRuleModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUpgradeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "toolNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeDurabilityIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradePowerIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeTool",
    data: BytesLike
  ): Result;
}

export namespace MinedEvent {
  export type InputTuple = [
    player: AddressLike,
    toolId: BigNumberish,
    toolType: BigNumberish,
    rewardAmount: BigNumberish,
    minedAt: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    toolId: bigint,
    toolType: bigint,
    rewardAmount: bigint,
    minedAt: bigint
  ];
  export interface OutputObject {
    player: string;
    toolId: bigint;
    toolType: bigint;
    rewardAmount: bigint;
    minedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParameterChangedEvent {
  export type InputTuple = [
    key: BytesLike,
    oldValue: BigNumberish,
    newValue: BigNumberish
  ];
  export type OutputTuple = [key: string, oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    key: string;
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleModuleUpdatedEvent {
  export type InputTuple = [ruleModule: AddressLike];
  export type OutputTuple = [ruleModule: string];
  export interface OutputObject {
    ruleModule: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MiningCore extends BaseContract {
  connect(runner?: ContractRunner | null): MiningCore;
  waitForDeployment(): Promise<this>;

  interface: MiningCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canMine: TypedContractMethod<[toolId: BigNumberish], [boolean], "view">;

  mine: TypedContractMethod<[toolId: BigNumberish], [void], "nonpayable">;

  mineBatch: TypedContractMethod<
    [toolIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingReward: TypedContractMethod<[toolId: BigNumberish], [bigint], "view">;

  resourceToken: TypedContractMethod<[], [string], "view">;

  rewardVault: TypedContractMethod<[], [string], "view">;

  ruleModule: TypedContractMethod<[], [string], "view">;

  setPaused: TypedContractMethod<[value: boolean], [void], "nonpayable">;

  setRuleModule: TypedContractMethod<
    [rules: AddressLike],
    [void],
    "nonpayable"
  >;

  setUpgradeConfig: TypedContractMethod<
    [
      cost: BigNumberish,
      powerIncrease: BigNumberish,
      durabilityIncrease: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  toolNFT: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeCost: TypedContractMethod<[], [bigint], "view">;

  upgradeDurabilityIncrease: TypedContractMethod<[], [bigint], "view">;

  upgradePowerIncrease: TypedContractMethod<[], [bigint], "view">;

  upgradeTool: TypedContractMethod<
    [toolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canMine"
  ): TypedContractMethod<[toolId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "mine"
  ): TypedContractMethod<[toolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mineBatch"
  ): TypedContractMethod<[toolIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingReward"
  ): TypedContractMethod<[toolId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "resourceToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ruleModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRuleModule"
  ): TypedContractMethod<[rules: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUpgradeConfig"
  ): TypedContractMethod<
    [
      cost: BigNumberish,
      powerIncrease: BigNumberish,
      durabilityIncrease: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "toolNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeDurabilityIncrease"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradePowerIncrease"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeTool"
  ): TypedContractMethod<[toolId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Mined"
  ): TypedContractEvent<
    MinedEvent.InputTuple,
    MinedEvent.OutputTuple,
    MinedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParameterChanged"
  ): TypedContractEvent<
    ParameterChangedEvent.InputTuple,
    ParameterChangedEvent.OutputTuple,
    ParameterChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RuleModuleUpdated"
  ): TypedContractEvent<
    RuleModuleUpdatedEvent.InputTuple,
    RuleModuleUpdatedEvent.OutputTuple,
    RuleModuleUpdatedEvent.OutputObject
  >;

  filters: {
    "Mined(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      MinedEvent.InputTuple,
      MinedEvent.OutputTuple,
      MinedEvent.OutputObject
    >;
    Mined: TypedContractEvent<
      MinedEvent.InputTuple,
      MinedEvent.OutputTuple,
      MinedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParameterChanged(bytes32,uint256,uint256)": TypedContractEvent<
      ParameterChangedEvent.InputTuple,
      ParameterChangedEvent.OutputTuple,
      ParameterChangedEvent.OutputObject
    >;
    ParameterChanged: TypedContractEvent<
      ParameterChangedEvent.InputTuple,
      ParameterChangedEvent.OutputTuple,
      ParameterChangedEvent.OutputObject
    >;

    "Paused(bool)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RuleModuleUpdated(address)": TypedContractEvent<
      RuleModuleUpdatedEvent.InputTuple,
      RuleModuleUpdatedEvent.OutputTuple,
      RuleModuleUpdatedEvent.OutputObject
    >;
    RuleModuleUpdated: TypedContractEvent<
      RuleModuleUpdatedEvent.InputTuple,
      RuleModuleUpdatedEvent.OutputTuple,
      RuleModuleUpdatedEvent.OutputObject
    >;
  };
}
