/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RewardVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canReserve"
      | "dailyEmissionCap"
      | "emissionEnd"
      | "emissionStart"
      | "emittedByDay"
      | "fund"
      | "miningCore"
      | "owner"
      | "paused"
      | "remainingRewards"
      | "reserve"
      | "seasonEmissionCap"
      | "seasonEmitted"
      | "setDailyEmissionCap"
      | "setMiningCore"
      | "setPaused"
      | "setSeasonEmissionCap"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MiningCoreUpdated"
      | "OwnershipTransferred"
      | "ParameterChanged"
      | "Paused"
      | "RewardFunded"
      | "RewardReserved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyEmissionCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emissionEnd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emissionStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emittedByDay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "miningCore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remainingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seasonEmissionCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seasonEmitted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyEmissionCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMiningCore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setSeasonEmissionCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "canReserve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dailyEmissionCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emissionEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emissionStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emittedByDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "miningCore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "seasonEmissionCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonEmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyEmissionCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMiningCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSeasonEmissionCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MiningCoreUpdatedEvent {
  export type InputTuple = [miningCore: AddressLike];
  export type OutputTuple = [miningCore: string];
  export interface OutputObject {
    miningCore: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParameterChangedEvent {
  export type InputTuple = [
    key: BytesLike,
    oldValue: BigNumberish,
    newValue: BigNumberish
  ];
  export type OutputTuple = [key: string, oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    key: string;
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardFundedEvent {
  export type InputTuple = [
    amount: BigNumberish,
    remainingRewards: BigNumberish
  ];
  export type OutputTuple = [amount: bigint, remainingRewards: bigint];
  export interface OutputObject {
    amount: bigint;
    remainingRewards: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardReservedEvent {
  export type InputTuple = [
    player: AddressLike,
    amount: BigNumberish,
    day: BigNumberish,
    seasonEmitted: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    amount: bigint,
    day: bigint,
    seasonEmitted: bigint
  ];
  export interface OutputObject {
    player: string;
    amount: bigint;
    day: bigint;
    seasonEmitted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardVault extends BaseContract {
  connect(runner?: ContractRunner | null): RewardVault;
  waitForDeployment(): Promise<this>;

  interface: RewardVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canReserve: TypedContractMethod<[amount: BigNumberish], [boolean], "view">;

  dailyEmissionCap: TypedContractMethod<[], [bigint], "view">;

  emissionEnd: TypedContractMethod<[], [bigint], "view">;

  emissionStart: TypedContractMethod<[], [bigint], "view">;

  emittedByDay: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  fund: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  miningCore: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  remainingRewards: TypedContractMethod<[], [bigint], "view">;

  reserve: TypedContractMethod<
    [player: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  seasonEmissionCap: TypedContractMethod<[], [bigint], "view">;

  seasonEmitted: TypedContractMethod<[], [bigint], "view">;

  setDailyEmissionCap: TypedContractMethod<
    [value: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMiningCore: TypedContractMethod<[core: AddressLike], [void], "nonpayable">;

  setPaused: TypedContractMethod<[value: boolean], [void], "nonpayable">;

  setSeasonEmissionCap: TypedContractMethod<
    [value: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canReserve"
  ): TypedContractMethod<[amount: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "dailyEmissionCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emissionEnd"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emissionStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emittedByDay"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "miningCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "remainingRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserve"
  ): TypedContractMethod<
    [player: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "seasonEmissionCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seasonEmitted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setDailyEmissionCap"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMiningCore"
  ): TypedContractMethod<[core: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSeasonEmissionCap"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MiningCoreUpdated"
  ): TypedContractEvent<
    MiningCoreUpdatedEvent.InputTuple,
    MiningCoreUpdatedEvent.OutputTuple,
    MiningCoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParameterChanged"
  ): TypedContractEvent<
    ParameterChangedEvent.InputTuple,
    ParameterChangedEvent.OutputTuple,
    ParameterChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RewardFunded"
  ): TypedContractEvent<
    RewardFundedEvent.InputTuple,
    RewardFundedEvent.OutputTuple,
    RewardFundedEvent.OutputObject
  >;
  getEvent(
    key: "RewardReserved"
  ): TypedContractEvent<
    RewardReservedEvent.InputTuple,
    RewardReservedEvent.OutputTuple,
    RewardReservedEvent.OutputObject
  >;

  filters: {
    "MiningCoreUpdated(address)": TypedContractEvent<
      MiningCoreUpdatedEvent.InputTuple,
      MiningCoreUpdatedEvent.OutputTuple,
      MiningCoreUpdatedEvent.OutputObject
    >;
    MiningCoreUpdated: TypedContractEvent<
      MiningCoreUpdatedEvent.InputTuple,
      MiningCoreUpdatedEvent.OutputTuple,
      MiningCoreUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParameterChanged(bytes32,uint256,uint256)": TypedContractEvent<
      ParameterChangedEvent.InputTuple,
      ParameterChangedEvent.OutputTuple,
      ParameterChangedEvent.OutputObject
    >;
    ParameterChanged: TypedContractEvent<
      ParameterChangedEvent.InputTuple,
      ParameterChangedEvent.OutputTuple,
      ParameterChangedEvent.OutputObject
    >;

    "Paused(bool)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RewardFunded(uint256,uint256)": TypedContractEvent<
      RewardFundedEvent.InputTuple,
      RewardFundedEvent.OutputTuple,
      RewardFundedEvent.OutputObject
    >;
    RewardFunded: TypedContractEvent<
      RewardFundedEvent.InputTuple,
      RewardFundedEvent.OutputTuple,
      RewardFundedEvent.OutputObject
    >;

    "RewardReserved(address,uint256,uint256,uint256)": TypedContractEvent<
      RewardReservedEvent.InputTuple,
      RewardReservedEvent.OutputTuple,
      RewardReservedEvent.OutputObject
    >;
    RewardReserved: TypedContractEvent<
      RewardReservedEvent.InputTuple,
      RewardReservedEvent.OutputTuple,
      RewardReservedEvent.OutputObject
    >;
  };
}
