/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RuleModuleV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "baseReward"
      | "calculateReward"
      | "cooldown"
      | "durabilityCost"
      | "levelMultiplierBps"
      | "powerMultiplierBps"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ParameterChanged"): EventFragment;

  encodeFunctionData(
    functionFragment: "baseReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReward",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cooldown", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "durabilityCost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "levelMultiplierBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "powerMultiplierBps",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "baseReward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cooldown", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "durabilityCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levelMultiplierBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "powerMultiplierBps",
    data: BytesLike
  ): Result;
}

export namespace ParameterChangedEvent {
  export type InputTuple = [
    key: BytesLike,
    oldValue: BigNumberish,
    newValue: BigNumberish
  ];
  export type OutputTuple = [key: string, oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    key: string;
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RuleModuleV1 extends BaseContract {
  connect(runner?: ContractRunner | null): RuleModuleV1;
  waitForDeployment(): Promise<this>;

  interface: RuleModuleV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  baseReward: TypedContractMethod<[], [bigint], "view">;

  calculateReward: TypedContractMethod<
    [power: BigNumberish, level: BigNumberish],
    [bigint],
    "view"
  >;

  cooldown: TypedContractMethod<[], [bigint], "view">;

  durabilityCost: TypedContractMethod<[], [bigint], "view">;

  levelMultiplierBps: TypedContractMethod<[], [bigint], "view">;

  powerMultiplierBps: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "baseReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateReward"
  ): TypedContractMethod<
    [power: BigNumberish, level: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "durabilityCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "levelMultiplierBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "powerMultiplierBps"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ParameterChanged"
  ): TypedContractEvent<
    ParameterChangedEvent.InputTuple,
    ParameterChangedEvent.OutputTuple,
    ParameterChangedEvent.OutputObject
  >;

  filters: {
    "ParameterChanged(bytes32,uint256,uint256)": TypedContractEvent<
      ParameterChangedEvent.InputTuple,
      ParameterChangedEvent.OutputTuple,
      ParameterChangedEvent.OutputObject
    >;
    ParameterChanged: TypedContractEvent<
      ParameterChangedEvent.InputTuple,
      ParameterChangedEvent.OutputTuple,
      ParameterChangedEvent.OutputObject
    >;
  };
}
