/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ToolNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activate"
      | "activateFromCore"
      | "activateOnMint"
      | "approve"
      | "balanceOf"
      | "buyTool"
      | "configureToolType"
      | "expiredTransferable"
      | "getApproved"
      | "isActive"
      | "isApprovedForAll"
      | "markUsed"
      | "miningCore"
      | "name"
      | "nextToolId"
      | "owner"
      | "ownerOf"
      | "setApprovalForAll"
      | "setMiningCore"
      | "symbol"
      | "tokenURI"
      | "toolDuration"
      | "toolTypes"
      | "tools"
      | "transferFrom"
      | "transferOwnership"
      | "upgradeFromCore"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "MiningCoreUpdated"
      | "OwnershipTransferred"
      | "ToolActivated"
      | "ToolMinted"
      | "ToolTypeConfigured"
      | "ToolUpgraded"
      | "ToolUsed"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activateFromCore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activateOnMint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configureToolType",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "expiredTransferable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markUsed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "miningCore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextToolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMiningCore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toolDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toolTypes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tools", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeFromCore",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "activate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activateFromCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateOnMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "configureToolType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expiredTransferable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markUsed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "miningCore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextToolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMiningCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toolDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "toolTypes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeFromCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MiningCoreUpdatedEvent {
  export type InputTuple = [miningCore: AddressLike];
  export type OutputTuple = [miningCore: string];
  export interface OutputObject {
    miningCore: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToolActivatedEvent {
  export type InputTuple = [
    toolId: BigNumberish,
    activatedAt: BigNumberish,
    expireAt: BigNumberish
  ];
  export type OutputTuple = [
    toolId: bigint,
    activatedAt: bigint,
    expireAt: bigint
  ];
  export interface OutputObject {
    toolId: bigint;
    activatedAt: bigint;
    expireAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToolMintedEvent {
  export type InputTuple = [
    player: AddressLike,
    toolId: BigNumberish,
    toolType: BigNumberish
  ];
  export type OutputTuple = [player: string, toolId: bigint, toolType: bigint];
  export interface OutputObject {
    player: string;
    toolId: bigint;
    toolType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToolTypeConfiguredEvent {
  export type InputTuple = [
    toolType: BigNumberish,
    price: BigNumberish,
    maxSupply: BigNumberish,
    power: BigNumberish,
    durability: BigNumberish
  ];
  export type OutputTuple = [
    toolType: bigint,
    price: bigint,
    maxSupply: bigint,
    power: bigint,
    durability: bigint
  ];
  export interface OutputObject {
    toolType: bigint;
    price: bigint;
    maxSupply: bigint;
    power: bigint;
    durability: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToolUpgradedEvent {
  export type InputTuple = [
    toolId: BigNumberish,
    oldLevel: BigNumberish,
    newLevel: BigNumberish
  ];
  export type OutputTuple = [
    toolId: bigint,
    oldLevel: bigint,
    newLevel: bigint
  ];
  export interface OutputObject {
    toolId: bigint;
    oldLevel: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToolUsedEvent {
  export type InputTuple = [
    toolId: BigNumberish,
    durabilityAfter: BigNumberish,
    lastUsedAt: BigNumberish
  ];
  export type OutputTuple = [
    toolId: bigint,
    durabilityAfter: bigint,
    lastUsedAt: bigint
  ];
  export interface OutputObject {
    toolId: bigint;
    durabilityAfter: bigint;
    lastUsedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ToolNFT extends BaseContract {
  connect(runner?: ContractRunner | null): ToolNFT;
  waitForDeployment(): Promise<this>;

  interface: ToolNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activate: TypedContractMethod<[toolId: BigNumberish], [void], "nonpayable">;

  activateFromCore: TypedContractMethod<
    [toolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  activateOnMint: TypedContractMethod<[], [boolean], "view">;

  approve: TypedContractMethod<
    [spender: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  buyTool: TypedContractMethod<[toolType: BigNumberish], [bigint], "payable">;

  configureToolType: TypedContractMethod<
    [
      toolType: BigNumberish,
      price: BigNumberish,
      maxSupply: BigNumberish,
      power: BigNumberish,
      durability: BigNumberish,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  expiredTransferable: TypedContractMethod<[], [boolean], "view">;

  getApproved: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  isActive: TypedContractMethod<[toolId: BigNumberish], [boolean], "view">;

  isApprovedForAll: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  markUsed: TypedContractMethod<
    [toolId: BigNumberish, durabilityCost: BigNumberish],
    [void],
    "nonpayable"
  >;

  miningCore: TypedContractMethod<[], [string], "view">;

  name: TypedContractMethod<[], [string], "view">;

  nextToolId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setMiningCore: TypedContractMethod<[core: AddressLike], [void], "nonpayable">;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  toolDuration: TypedContractMethod<[], [bigint], "view">;

  toolTypes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string, boolean] & {
        price: bigint;
        maxSupply: bigint;
        minted: bigint;
        power: bigint;
        durability: bigint;
        metadataURI: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  tools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        toolType: bigint;
        mintedAt: bigint;
        activatedAt: bigint;
        expireAt: bigint;
        power: bigint;
        durability: bigint;
        level: bigint;
        lastUsedAt: bigint;
      }
    ],
    "view"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeFromCore: TypedContractMethod<
    [
      toolId: BigNumberish,
      powerIncrease: BigNumberish,
      durabilityIncrease: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activate"
  ): TypedContractMethod<[toolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activateFromCore"
  ): TypedContractMethod<[toolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activateOnMint"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyTool"
  ): TypedContractMethod<[toolType: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "configureToolType"
  ): TypedContractMethod<
    [
      toolType: BigNumberish,
      price: BigNumberish,
      maxSupply: BigNumberish,
      power: BigNumberish,
      durability: BigNumberish,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expiredTransferable"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[toolId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "markUsed"
  ): TypedContractMethod<
    [toolId: BigNumberish, durabilityCost: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "miningCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextToolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMiningCore"
  ): TypedContractMethod<[core: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "toolDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "toolTypes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string, boolean] & {
        price: bigint;
        maxSupply: bigint;
        minted: bigint;
        power: bigint;
        durability: bigint;
        metadataURI: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        toolType: bigint;
        mintedAt: bigint;
        activatedAt: bigint;
        expireAt: bigint;
        power: bigint;
        durability: bigint;
        level: bigint;
        lastUsedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeFromCore"
  ): TypedContractMethod<
    [
      toolId: BigNumberish,
      powerIncrease: BigNumberish,
      durabilityIncrease: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "MiningCoreUpdated"
  ): TypedContractEvent<
    MiningCoreUpdatedEvent.InputTuple,
    MiningCoreUpdatedEvent.OutputTuple,
    MiningCoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ToolActivated"
  ): TypedContractEvent<
    ToolActivatedEvent.InputTuple,
    ToolActivatedEvent.OutputTuple,
    ToolActivatedEvent.OutputObject
  >;
  getEvent(
    key: "ToolMinted"
  ): TypedContractEvent<
    ToolMintedEvent.InputTuple,
    ToolMintedEvent.OutputTuple,
    ToolMintedEvent.OutputObject
  >;
  getEvent(
    key: "ToolTypeConfigured"
  ): TypedContractEvent<
    ToolTypeConfiguredEvent.InputTuple,
    ToolTypeConfiguredEvent.OutputTuple,
    ToolTypeConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "ToolUpgraded"
  ): TypedContractEvent<
    ToolUpgradedEvent.InputTuple,
    ToolUpgradedEvent.OutputTuple,
    ToolUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "ToolUsed"
  ): TypedContractEvent<
    ToolUsedEvent.InputTuple,
    ToolUsedEvent.OutputTuple,
    ToolUsedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "MiningCoreUpdated(address)": TypedContractEvent<
      MiningCoreUpdatedEvent.InputTuple,
      MiningCoreUpdatedEvent.OutputTuple,
      MiningCoreUpdatedEvent.OutputObject
    >;
    MiningCoreUpdated: TypedContractEvent<
      MiningCoreUpdatedEvent.InputTuple,
      MiningCoreUpdatedEvent.OutputTuple,
      MiningCoreUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ToolActivated(uint256,uint256,uint256)": TypedContractEvent<
      ToolActivatedEvent.InputTuple,
      ToolActivatedEvent.OutputTuple,
      ToolActivatedEvent.OutputObject
    >;
    ToolActivated: TypedContractEvent<
      ToolActivatedEvent.InputTuple,
      ToolActivatedEvent.OutputTuple,
      ToolActivatedEvent.OutputObject
    >;

    "ToolMinted(address,uint256,uint256)": TypedContractEvent<
      ToolMintedEvent.InputTuple,
      ToolMintedEvent.OutputTuple,
      ToolMintedEvent.OutputObject
    >;
    ToolMinted: TypedContractEvent<
      ToolMintedEvent.InputTuple,
      ToolMintedEvent.OutputTuple,
      ToolMintedEvent.OutputObject
    >;

    "ToolTypeConfigured(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ToolTypeConfiguredEvent.InputTuple,
      ToolTypeConfiguredEvent.OutputTuple,
      ToolTypeConfiguredEvent.OutputObject
    >;
    ToolTypeConfigured: TypedContractEvent<
      ToolTypeConfiguredEvent.InputTuple,
      ToolTypeConfiguredEvent.OutputTuple,
      ToolTypeConfiguredEvent.OutputObject
    >;

    "ToolUpgraded(uint256,uint256,uint256)": TypedContractEvent<
      ToolUpgradedEvent.InputTuple,
      ToolUpgradedEvent.OutputTuple,
      ToolUpgradedEvent.OutputObject
    >;
    ToolUpgraded: TypedContractEvent<
      ToolUpgradedEvent.InputTuple,
      ToolUpgradedEvent.OutputTuple,
      ToolUpgradedEvent.OutputObject
    >;

    "ToolUsed(uint256,uint256,uint256)": TypedContractEvent<
      ToolUsedEvent.InputTuple,
      ToolUsedEvent.OutputTuple,
      ToolUsedEvent.OutputObject
    >;
    ToolUsed: TypedContractEvent<
      ToolUsedEvent.InputTuple,
      ToolUsedEvent.OutputTuple,
      ToolUsedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
