/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../common";
import type { RuleModuleV1, RuleModuleV1Interface } from "../RuleModuleV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "initialBaseReward",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initialCooldown",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initialDurabilityCost",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initialLevelMultiplierBps",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initialPowerMultiplierBps",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldValue",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "ParameterChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "baseReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "power",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
    ],
    name: "calculateReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cooldown",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "durabilityCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "levelMultiplierBps",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "powerMultiplierBps",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080346100eb57601f61030638819003918201601f19168301916001600160401b038311848410176100f05780849260a0946040528339810103126100eb578051906020810151604082015190608060608401519301519380156100b8578215610081576000556001556002556003556004556040516101ff90816101078239f35b60405162461bcd60e51b815260206004820152600f60248201526e4455524142494c4954595f5a45524f60881b6044820152606490fd5b60405162461bcd60e51b815260206004820152600b60248201526a5245574152445f5a45524f60a81b6044820152606490fd5b600080fd5b634e487b7160e01b600052604160045260246000fdfe608060408181526004918236101561001657600080fd5b600092833560e01c91826313871f0e146101845750816313ed0846146100e657816376ad03bc146100c9578163787a08a6146100aa578163ee87bad514610088575063f316a9fb1461006757600080fd5b346100845781600319360112610084576020906003549051908152f35b5080fd5b9050346100a657826003193601126100a65760209250549051908152f35b8280fd5b5050346100845781600319360112610084576020906001549051908152f35b505034610084578160031936011261008457602091549051908152f35b828434610181578160031936011261018157602435610107845485356101a0565b916127109283019182841161016e57600019810190811161016e5760035461012e916101a0565b830180931161015b576020939261014e6305f5e1009361015393546101a0565b6101a0565b049051908152f35b634e487b7160e01b815260118552602490fd5b634e487b7160e01b825260118652602482fd5b80fd5b8490346100845781600319360112610084576020906002548152f35b818102929181159184041417156101b357565b634e487b7160e01b600052601160045260246000fdfea26469706673582212209239d5b5d02086906929b05e8faa5441120c6c0dd9d639502eca0aa9b4fb03ac64736f6c63430008180033";

type RuleModuleV1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RuleModuleV1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RuleModuleV1__factory extends ContractFactory {
  constructor(...args: RuleModuleV1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    initialBaseReward: BigNumberish,
    initialCooldown: BigNumberish,
    initialDurabilityCost: BigNumberish,
    initialLevelMultiplierBps: BigNumberish,
    initialPowerMultiplierBps: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      initialBaseReward,
      initialCooldown,
      initialDurabilityCost,
      initialLevelMultiplierBps,
      initialPowerMultiplierBps,
      overrides || {}
    );
  }
  override deploy(
    initialBaseReward: BigNumberish,
    initialCooldown: BigNumberish,
    initialDurabilityCost: BigNumberish,
    initialLevelMultiplierBps: BigNumberish,
    initialPowerMultiplierBps: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      initialBaseReward,
      initialCooldown,
      initialDurabilityCost,
      initialLevelMultiplierBps,
      initialPowerMultiplierBps,
      overrides || {}
    ) as Promise<
      RuleModuleV1 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RuleModuleV1__factory {
    return super.connect(runner) as RuleModuleV1__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RuleModuleV1Interface {
    return new Interface(_abi) as RuleModuleV1Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RuleModuleV1 {
    return new Contract(address, _abi, runner) as unknown as RuleModuleV1;
  }
}
